export * from './iIcons'
export * from './rIcons'
export * from './tIcons'
export * from './fIcons'
export * from './aicons'
export * from './mIcons '
export * from './gIcons'
export * from './sIcons'
export * from './bIcons'