"""add rol to users

Revision ID: 376045fb3e2a
Revises: 59a6ed235285
Create Date: 2026-08-25 22:41:52.612696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376045fb3e2a'
down_revision = '59a6ed235285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
