"""auto migration 2026-08-25T01:49:02.640Z

Revision ID: 571a6ec1c22a
Revises: 53c43e38898b
Create Date: 2026-08-24 20:49:03.581389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571a6ec1c22a'
down_revision = '53c43e38898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'terms_accepted_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP')
        ))
        batch_op.add_column(sa.Column(
            'age_confirmed_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP')
        ))
        batch_op.add_column(sa.Column('terms_version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('terms_version')
        batch_op.drop_column('age_confirmed_at')
        batch_op.drop_column('terms_accepted_at')

    # ### end Alembic commands ###
