"""auto migration 2026-08-26T01:42:37.852Z

Revision ID: 993172c243b3
Revises: fcf977e01b45
Create Date: 2026-08-25 20:42:38.874349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993172c243b3'
down_revision = 'fcf977e01b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.drop_column('locked_until')

    # ### end Alembic commands ###
