"""auto migration 2026-08-25T21:03:24.267Z

Revision ID: a96f2e74e32d
Revises: 571a6ec1c22a
Create Date: 2026-08-25 16:03:25.214609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96f2e74e32d'
down_revision = '571a6ec1c22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
